[package]
name = "let_engine_test"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
let-engine = { path = "../Let-Engine/engine", features = [ "egui" ] }
spin_sleep = "1.1.1"
hashbrown = "0.14.0"

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
