[package]
name = "let_engine_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
let-engine = {path = "../Let-Engine"}
parking_lot = "0.12.1"
winit = "0.28.5"

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
