# example config.toml located in the assets folder when the assets-system feature is enabled.

# biggest size in megabytes before splitting the resources into the next file
max_size = 30_000_000


# file names of the resource files
# %g - group
# %i - index
# when `split_by_group` is false `%g` is "asset"
naming = "%gs%i"

output = "assets"

# Excludes specific files or directories from being packed
exclude = ["textures/shidkitty69.png"]

# groups and paths to folders where those groups get defined
[groups]
texture = "textures"
sound = "sounds"
font = "fonts"

